version: '3.8'

services: 
  database:
    container_name: mysqldb
    image: mysql:5.7
 
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timeSheetDevOps
    ports:
      - 3307:3306
    
  app:  
    container_name: timesheet
    image: "timesheet"

    depends_on:
      - database
    ports:
      - 8089:8089
    environment: 
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/timeSheetDevOps?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5Dialect"
      }'

#   jenkins:
#     image: jenkins/jenkins:lts
#     restart: on-failure
#     privileged: true
#     user: root
#     ports:
#       - '8079:8080'
#       - '50000:50000'
#     container_name: jenkins
#     networks:
#       - timesheet-net
#     volumes:
#       - ~/jenkins:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /usr/bin/docker:/usr/bin/docker

#   nexus:
#     image: sonatype/nexus3
#     restart: on-failure
#     networks:
#       - timesheet-net
#     volumes:
#       - "nexus-data:/nexus-data"
#     ports:
#       - "8082:8081"
#       - "8083:8083"

#   sonarqube:
#     image: sonarqube:9.1-community
#     restart: on-failure
#     depends_on: 
#       - init
#     networks:
#       - timesheet-net
#     volumes:
#       - "nexus-data:/nexus-data"
#     ports:
#       - "9001:9000"
#     volumes:
#       - sonarqube_conf:/opt/sonarqube/conf
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

#   init:
#     image: bash
#     privileged: true
#     user: root
#     volumes:
#       - ./scripts/sonarqube/init.sh:/opt/init-sonarqube.sh
#     command: [ "sh", "-e", "/opt/init-sonarqube.sh" ]

# networks:
#   timesheet-net:
# volumes:
#   jenkins:
#   nexus-data:
#   sonarqube_bundled-plugins:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_db:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp:

  